### ISSUE TITLE
method request() not work

### ISSUE THREAD

**Issue by madun92** [UniSharp/laravel-filemanager#214]

**Comment by g0110280** [comment]
@madun92 Can you provide the version number of your Laravel?

**Comment by madun92** [comment]
L 5.4.13 & Lfm 1.7 , like issue #211 in latest comments, i think this problem placed in lfm controller construct

```
if (!$this->isProcessingImages() && !$this->isProcessingFiles()) {
   throw new \Exception('unexpected type parameter');
  }
```
which in view index request return as empty value

`<input type='hidden' name='type' id='type' value="{{ request('type') }}">`

or i miss something?
thanks @g0110280

**Comment by g0110280** [comment]
Fixed in `v1.7.6`.

**Comment by alisyahbana** [comment]
Hello i was using Laravel 5.0 and lfm 1.8.0, but i still get this error

> 
> FatalErrorException in LfmHelpers.php line 335:
> Call to undefined function Unisharp\Laravelfilemanager\traits\request()

**Comment by g0110280** [comment]
@alisyahbana please use [laravel-50 branch](https://github.com/UniSharp/laravel-filemanager/tree/laravel-50) of this package.
