### ISSUE TITLE
Invalid upload request 

### ISSUE THREAD

**Issue by ARNolasco** [UniSharp/laravel-filemanager#696]
I have this issue "Invalida upload request", some people mention the problem is de exif extension but according to phpinfo() the extension php-exif in enable. There is something else that can provoke this error.  Mi project work fine in my local but in my web site (sharing-host) do not upload new photos. Thanks in advance for the help.

![image](https://user-images.githubusercontent.com/43589229/46046699-aac7cf80-c0e7-11e8-8291-1c7a2bc2bbb2.png)

_Originally posted by @ARNolasco in https://github.com/UniSharp/laravel-filemanager/issues/475#issuecomment-424516837_

**Comment by S-Arif** [comment]
I am having same issue in laravel 5.7. please give some solution. for sure i have all extension enabled like **fileinfo, exif, gd2** i took my 3 hours now. please save my time.

**Comment by docmojoman** [comment]
I am also having the same problem. I am running Laravel 5.6.38. I also have gd2, exif and fileinfo enabled on my valet setup. 

![screen shot 2018-10-11 at 3 31 15 am](https://user-images.githubusercontent.com/3960863/46788257-c2b66a80-cd07-11e8-92ae-3132031290d9.png)

**Debugging**
Earlier posts referring to this same problem mention a debug binary in the ./version path `php ./vendor/unisharp/laravel-filemanager/bin/debug`, but it doesn't exist in this version (1.9.2) of laravel-filemanager.

Is there a way to do debug this version?

**Comment by g0110280** [comment]
If you are using `v2.0.0-alpha4`, there is a bug which will cause "Invalid upload request". Please upgrade to `v2.0.0-alpha5`.

**Comment by oleghalin** [comment]
I am using alpha5, still have this bug with Digital Ocean Spaces Storage disk.

**Comment by oleghalin** [comment]
@g0110280 

> If you are using `v2.0.0-alpha4`, there is a bug which will cause "Invalid upload request". Please upgrade to `v2.0.0-alpha5`.

I am using alpha5, still have this bug with Digital Ocean Spaces Storage disk.

**Comment by docmojoman** [comment]
> @g0110280
> 
> > If you are using `v2.0.0-alpha4`, there is a bug which will cause "Invalid upload request". Please upgrade to `v2.0.0-alpha5`.
> 
> I am using alpha5, still have this bug with Digital Ocean Spaces Storage disk.

Did you run `php artisan storage:link` ?

**Comment by docmojoman** [comment]
> > @oleghalin
> > > I am using alpha5, still have this bug with Digital Ocean Spaces Storage disk.
> > 
> > 
> > Did you run `php artisan storage:link` ?
> 
> @docmojoman yes, i am, btw i am using DO Spaces

alpha5 fixed my local installation.  When I deployed to my Digital Ocean (I don't use Spaces) server I forgot to run `storage:link` and I was getting blank uploads.

**Comment by dev-itbinc** [comment]
This bug exist only on cloud storage drivers

**Comment by nebed** [comment]
@docmojoman I still have this error on alpha5, please how do i fix? I use Amazon s3 storage, when i use local server storage it works fine, but once i link s3 it happens.

**Comment by mnightingale** [comment]
If using v2 this may have been fixed by #712 if you are using S3 and have thumbnails enabled.

**Comment by oleghalin** [comment]
@mnightingale i will test it ASAP and let you know

**Comment by JunaidQadirB** [comment]
It was a permission issue. making the `public/files` and `public/photos` folders writable solved the issue for me.

**Comment by gelinger777** [comment]
I have the latest dev-master and on s3 Amazon I am getting invalid upload request

**Comment by aleksandrpashkovskiy** [comment]
From the root folder of the project, try typing in the command line
```
sudo chown -R $USERNAME:www-data public/images
chmod -R 775 public/images
```
where USERNAME - your user (eg. "root")

**Comment by maxbluetang** [comment]
If on Windows, go into your php ini and set this: upload_tmp_dir = "C:\Users\{my_user}\AppData\Local\Temp"  
StackOverflow Ref:https://stackoverflow.com/questions/45619248/laravel-5-4-fopen-filename-cannot-be-empty

**Comment by faysal-web** [comment]
I also face this problem. I think all shared hosting occur this problem. But no one gives a specific solution.

**Comment by abishekrsrikaanth** [comment]
I am on the latest version of the package. My disk on `lfm.php` is set to `s3` and I get this error. If I set to public, then the upload works fine by the images are blank. I have run `storage:link` before doing this. The `should_create_thumbnails` is set to `false`

**Comment by abishekrsrikaanth** [comment]
Got this to work with PR https://github.com/UniSharp/laravel-filemanager/pull/982

**Comment by isa95Ar** [comment]
when you run `php artisan storage:link` your folder permission is going to the hell, run `chmod -R 775 your_folder/` and `sudo chown -R your_user:your_user your_folder/` can't use root :p

**Comment by JDsWebService** [comment]
For anyone that is having this issue... You can solve this by making sure your re-change your permissions on your folders.

```
read -p 'Site: ' site &&
sudo chown -R :www-data /var/www/$site &&
sudo chmod -R 777 /var/www/$site/storage &&
sudo chmod -R 777 /var/www/$site/bootstrap/cache
```

**Comment by streamtw** [comment]
Looks like a solved issue. Please leave comments or reopen this if it is still a issue.

**Comment by atif987** [comment]
I am facing the same issue : "Invalid upload Request" . My version is : * v2.9.1 . Using Laravel version 9 . Running project on local machine . With that error , some times the image get saved , sometime
![sd](https://github.com/user-attachments/assets/5d36a4be-d2cf-4efe-ba92-cc93e26e16fd)
 not .
