### ISSUE TITLE
File manager doesn't refresh after successful image upload

### ISSUE THREAD

**Issue by stinkymonkeyph** [UniSharp/laravel-filemanager#872]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system :
 * Laravel version :
 * Package version :
 * Steps to reproduce your issue :
 * Screenshots of browser console :

Operating System: Windows 10
Laravel version:  6.2
Package version: 1.9.2

Steps to reproduce

1. Used both ckeditor and tinymce, after any successful image upload file manager doesn't refresh. List of images is not updated.

![image](https://user-images.githubusercontent.com/20766001/73239670-c52c2480-41d7-11ea-8cd1-b844fe13422a.png)

**Comment by HalfBottleOfMind** [comment]
Fixed in #858

**Comment by stinkymonkeyph** [comment]
But the issue is still there when you install the latest version

**Comment by wiklog** [comment]
In UploadController.php replace `return $response;` by `return json_encode($response);`

**Comment by stinkymonkeyph** [comment]
> In UploadController.php replace `return $response;` by `return json_encode($response);`

Hi, should we make a PR for this? I see solutions but the issue is still there.

**Comment by wiklog** [comment]
I made a proposal, I await validation




Wiklog




Stéphane Hervy


06 12 55 57 54


https://wiklog.fr







On Fri, Feb 7, 2020 at 12:47 AM +0100, "Nelmin Jay Magan Anoc" <notifications@github.com> wrote:













In UploadController.php replace return $response; by return json_encode($response);



Hi, should we make a PR for this? I see solutions but the issue is still there.

**Comment by wiklog** [comment]
PR #878 done

**Comment by soheilyou** [comment]
the issue is still there, I'm using  `composer require unisharp/laravel-filemanager` to get the package, and this issue is still there!
how can I get the fix?

**Comment by itsowaisnoor** [comment]
i am using version 2.0 and i am getting this problem can anybody help. After uploading the image **(Upload File(s))** remains these and didn't refresh now i have to reload it manually.

Please Suggest Something

**Comment by flaviopc** [comment]
See #921
